In [20]:
from google import genai
from google.genai import types
from PIL import Image

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [21]:
# 1. Initialize the client (automatically picks up GEMINI_API_KEY from environment)
client = genai.Client(
    vertexai=True,
    project="infinitas-ds-ai-poc",
    location="us-central1",
)

In [22]:
# 2. Open your local image file

path_batch1 = ["test_images/First_Tamper.png", "test_images/first-tamper.png", "test_images/pink.png","test_images/combined.png",
         "test_images/neat.png", "test_images/neatest.png", "test_images/cropped-obvious.png"] # explore strength and weaknesses

path_batch2 = ["test_images/payslip1.jpeg", "test_images/payslip10.jpeg", "test_images/payslip2.png",
               "test_images/payslip20.png","test_images/payslip3.png", "test_images/payslip30.png"] # explore payslip with white space but different fonts

paths = path_batch1
images = []

for path in paths:
    images.append(Image.open(path))

print(len(images))

7

## Ground truth labels

Set the true `label` ("tampered" / "authentic") and `label_signals` (true signal types present, if tampered) for each image in this batch. Stored in `image_labels.json`, keyed by image path.

`log_result()` looks these up by `image_path` automatically when logging — they are for analysis only and are **never** included in the prompt/model call. Run this once per image (re-running just overwrites with the same value).

In [23]:
# # Only need to set up after making a new image once after it's been created.

# from result_logger import set_image_label, load_image_labels

# # Fill in the real ground truth for each image in `paths` below.
# # label: "tampered" or "authentic"
# # label_signals: list of signal types actually present (only meaningful if "tampered")
# #   -- see EXPECTED_SIGNAL_TYPES in result_logger.py for valid values

# ground_truth: dict[str, tuple[str, list[str]]] = {
#     paths[0]: ("authentic", []),
#     paths[1]: ("tampered", ["background_overlay", "font_weight_inconsistency",]),
#     paths[2]: ("tampered", ["background_overlay", "font_weight_inconsistency"]),
#     paths[3]: ("tampered", ["background_overlay", "font_weight_inconsistency"]),
#     paths[4]: ("tampered", ["font_weight_inconsistency","baseline_mismatch"]),
#     paths[5]: ("tampered", ["font_weight_inconsistency"]),
#     paths[6]: ("tampered", ["background_overlay", "font_weight_inconsistency", "baseline_mismatch"]),
# }

# for image_path, (label, label_signals) in ground_truth.items():
#     set_image_label(image_path, label, label_signals)

# load_image_labels()

In [24]:
# Read the V1 prompt

with open("prompt-library/V1.txt", "r", encoding="utf-8") as file:
    file_content = file.read()

prompt_v1 = file_content
print(type(prompt_v1))

# Read the V1 prompt split into system instruction + task prompt

with open("prompt-library/V1_system.txt", "r", encoding="utf-8") as file:
    system_prompt_v1 = file.read()

with open("prompt-library/V1_task.txt", "r", encoding="utf-8") as file:
    task_prompt_v1 = file.read()

<class 'str'>

## Result logging

Every model call below is logged to `notebook_results/results_log.jsonl` via `result_logger.log_result()`.
This keeps a permanent record across batches without cluttering this notebook.

**For each new batch of images:**
1. Bump `BATCH_ID` below (e.g. `"batch2"`)
2. Update `paths` in the image-loading cell to point at the new images
3. Re-run the experiment cells as usual — results from previous batches stay in the log

Use the "Review logged results" section at the end to compare across batches.

In [25]:
import time
from result_logger import log_result, load_results

BATCH_ID = "batch1"  # bump this for each new set of test images

## Try with the same model for now to test the workflow
### Models (to double check)
- "gemini-2.5-flash"
- "gemini-2.5-pro"
- "gemini-3.5-flash"
- "gemini-3.5-pro"

In [15]:
image_list = list(zip(paths, images))  

for image_path, image in image_list:

    start = time.perf_counter()

    # 3. Generate content by passing both the image object and your text prompt
    response = client.models.generate_content(
        model="gemini-2.5-pro",
        contents=[
            prompt_v1,
            image
        ], config = types.GenerateContentConfig(
            temperature = 0.1 # To change to variable this later
        )
    )

    latency_s = round(time.perf_counter() - start, 2)

    # 4. Print the text result
    print(response.text)

    log_result(
        batch_id=BATCH_ID,
        image_path=image_path,
        prompt_id="V1",
        model="gemini-2.5-pro",
        temperature=0.1,
        raw_response=response.text,
        latency_s=latency_s,
    )

```json
{
  "verdict": "authentic",
  "confidence": "high",
  "reasoning": "The document was scanned to establish a typographic baseline. All text appears to be rendered in the same font family, with consistent sharpness, weight, and resolution. The title is slightly larger, which is a standard formatting choice. The body text, including the address and the date, is uniform. There are no color or contrast discontinuities, no mismatched backgrounds, and no pixelation anomalies around any characters or numbers. The Thai numerals in the postal code and the date blend seamlessly with the surrounding text. Overall, there is no visual evidence to suggest any part of the text was digitally altered after the document's initial creation.",
  "signals_detected": [],
  "notes": "The document is a very clean, digitally-generated image. This high quality makes it easier to spot inconsistencies, and none were found. The 'authentic' verdict refers only to the absence of post-recapture digital tampering."
}
```
```json
{
  "verdict": "tampered",
  "confidence": "high",
  "reasoning": "A baseline typography was established by observing the consistent font, weight, and sharpness of the text in the title and address lines. A significant deviation from this baseline is observed in the date line. The text for the month and year, 'พฤศจิกายน ๒๕๖๙', is rendered on top of a solid grey rectangular background. This background is not part of the original document's design, which is otherwise plain white. This indicates that the original date was obscured by the grey box, and new text was digitally inserted on top of it.",
  "signals_detected": [
    {
      "signal_type": "color_contrast_discontinuity",
      "location": "The date line, specifically under the text 'พฤศจิกายน ๒๕๖๙' (November 2569).",
      "severity": "high"
    }
  ],
  "notes": "The grey box is a clear and unambiguous indicator of digital alteration, likely intended to redact or replace the original date."
}
```
```json
{
  "verdict": "tampered",
  "confidence": "high",
  "reasoning": "A baseline typography was established by examining the main body of the document, which shows consistent font weight, sharpness, and style. A significant deviation from this baseline was identified in the date line. The year '๒๕๖๘' is enclosed within a solid purple rectangular box, which is a stark color and background discontinuity inconsistent with a standard document. Furthermore, the text '๒๕๖๘' inside this box appears sharper and has different anti-aliasing properties compared to the adjacent text 'มิถุนายน', suggesting it was rendered and inserted separately. The combination of an anomalous background element and inconsistent text rendering at the same location provides strong evidence of digital alteration.",
  "signals_detected": [
    {
      "signal_type": "color_contrast_discontinuity",
      "location": "The year '๒๕๖๘' in the date line is placed inside a solid purple rectangular box.",
      "severity": "high"
    },
    {
      "signal_type": "resolution_mismatch",
      "location": "The text '๒๕๖๘' within the purple box in the date line exhibits different sharpness and anti-aliasing compared to the surrounding text.",
      "severity": "medium"
    }
  ],
  "notes": "The document appears to be digitally generated rather than a scan of a physical paper. The tampering is interpreted as a modification to the original digital file."
}
```
```json
{
  "verdict": "tampered",
  "confidence": "high",
  "reasoning": "The document's baseline consists of black text on a plain white background. The analysis identified two areas with blatant digital modifications. Both the month in the date line ('พฤศจิกายน') and the loan amount in numerals ('๖๐๐,๐๐๐') are rendered as white text inside solid grey rectangular boxes. These boxes are visually inconsistent with the surrounding text and the document's overall style, indicating they were digitally inserted after the document's initial creation. The numeric value '๖๐๐,๐๐๐' also contradicts the amount written out in words ('ห้าแสนบาทถ้วน', meaning five hundred thousand), which further supports the conclusion that the numeric value was altered.",
  "signals_detected": [
    {
      "signal_type": "color_contrast_discontinuity",
      "location": "The month 'พฤศจิกายน' in the date line is presented as white text within a grey box, contrasting with the surrounding black text on a white background.",
      "severity": "high"
    },
    {
      "signal_type": "color_contrast_discontinuity",
      "location": "The loan amount '๖๐๐,๐๐๐' in the main paragraph is presented as white text within a grey box, which is inconsistent with the rest of the paragraph's black text.",
      "severity": "high"
    }
  ],
  "notes": "The logical contradiction between the altered numeric value (600,000) and the original written-out value (five hundred thousand) serves as corroborating, non-visual evidence for the tampering detected through visual analysis."
}
```
```json
{
  "verdict": "tampered",
  "confidence": "high",
  "reasoning": "A baseline analysis of the document shows a consistent, sharp, and uniform typography throughout most of the text. However, a detailed examination of the date line reveals a clear anomaly. The word 'พฤศจิกายน' (November) exhibits a noticeably heavier font weight and slightly different anti-aliasing compared to the adjacent text on the same line ('วันที่ ๙ มิถุ' and '๒๕๖๙') and the rest of the document. This localized typographic inconsistency is a strong visual indicator that this specific word was digitally inserted or altered.",
  "signals_detected": [
    {
      "signal_type": "font_weight_inconsistency",
      "location": "The word 'พฤศจิกายน' in the date line.",
      "severity": "high"
    }
  ],
  "notes": "The date line is semantically unusual, containing what appears to be an incomplete month ('มิถุ') followed by a full month ('พฤศจิกายน'). While this adds to the suspicion, the tampering conclusion is based solely on the visual evidence of the inconsistent font weight."
}
```
```json
{
  "verdict": "tampered",
  "confidence": "high",
  "reasoning": "The document's text establishes a consistent baseline typography with sharp, clean edges. However, two specific numerical regions deviate significantly from this baseline. The monetary amount '๕๐๐,๐๐๐' in the main paragraph is noticeably blurrier and appears to have a different rendering quality (thicker lines, more pronounced anti-aliasing) than the surrounding Thai characters. This suggests a resolution mismatch, a strong indicator of digital insertion. A similar, though less severe, inconsistency is present in the date line, where the numbers for the day ('๙') and year ('๒๕๖๙') are less sharp than the text for the month. The localization of these artifacts to specific numerical values is compelling evidence of tampering.",
  "signals_detected": [
    {
      "signal_type": "resolution_mismatch",
      "location": "The numerical amount '๕๐๐,๐๐๐' in the main body paragraph.",
      "severity": "high"
    },
    {
      "signal_type": "resolution_mismatch",
      "location": "The numbers '๙' and '๒๕๖๙' in the date line.",
      "severity": "medium"
    }
  ],
  "notes": "The tampering is most evident in the different anti-aliasing and sharpness of the inserted numbers compared to the original text. The effect is most pronounced on the monetary value."
}
```
```json
{
  "verdict": "tampered",
  "confidence": "high",
  "reasoning": "The document's baseline typography is a consistent serif font used for all Thai text. A clear deviation is observed on the fourth line where the number '500,000' is displayed. This number is rendered in a sans-serif font, creating a stark typographical mismatch with the surrounding serif characters. Additionally, the edges of the numbers '500,000' are noticeably more pixelated and less sharp than the adjacent text, indicating a resolution mismatch. These combined signals strongly suggest that the number was digitally inserted after the document's original generation.",
  "signals_detected": [
    {
      "signal_type": "other",
      "location": "The number '500,000' on the fourth line.",
      "severity": "high"
    },
    {
      "signal_type": "resolution_mismatch",
      "location": "The number '500,000' on the fourth line.",
      "severity": "medium"
    }
  ],
  "notes": "The primary signal, classified as 'other', is a font family mismatch. The sans-serif font of the number '500,000' is inconsistent with the serif font of the rest of the document. The grey box obscuring part of the number is an artifact of the provided image and was ignored in favor of analyzing the underlying text's properties."
}
```

In [16]:
# V1 split: persona passed as system_instruction, task prompt as the user turn

image_list = list(zip(paths, images))  # image 1 and 2

for image_path, image in image_list:
    start = time.perf_counter()

    response = client.models.generate_content(
        model="gemini-2.5-pro",
        contents=[task_prompt_v1, image],
        config=types.GenerateContentConfig(
            system_instruction=system_prompt_v1,
            temperature = 0.1
        ),
    )

    latency_s = round(time.perf_counter() - start, 2)

    print(response.text)

    log_result(
        batch_id=BATCH_ID,
        image_path=image_path,
        prompt_id="V1_split",
        model="gemini-2.5-pro",
        temperature=0.1,
        raw_response=response.text,
        latency_s=latency_s,
    )

```json
{
  "verdict": "authentic",
  "confidence": "high",
  "reasoning": "I performed a thorough visual analysis of the document. The typography, including font type, weight, sharpness, and color, is consistent across all three lines of text. The background is a uniform white with no evidence of color or contrast discontinuities that would suggest text has been pasted or altered. The character edges are uniformly crisp, and there are no resolution mismatches between different words or numbers. The spacing and alignment of all text elements appear natural and consistent with a document created in a single session. No visual signals of post-recapture digital modification were found.",
  "signals_detected": [],
  "notes": "The image quality is extremely high, suggesting it is a direct digital export or a 'born-digital' document rather than a scan or photograph of a physical paper. This high level of clarity makes it easier to confirm the absence of tampering artifacts."
}
```
```json
{
  "verdict": "tampered",
  "confidence": "high",
  "reasoning": "The overall document typography is consistent, with a clean, sharp, black font on a white background. However, a clear visual anomaly is present in the date line at the bottom. The text for the month and year, 'พฤศจิกายน ๒๕๖๙', is superimposed on a solid grey rectangular box. This box has sharp, artificial edges and a background color that is inconsistent with the rest of the document's white background. This is a definitive sign of digital alteration, where a section was likely covered or highlighted with a shape tool and new text was placed on top.",
  "signals_detected": [
    {
      "signal_type": "color_contrast_discontinuity",
      "location": "The background of the date line, specifically behind the month and year ('พฤศจิกายน ๒๕๖๙').",
      "severity": "high"
    }
  ],
  "notes": "The alteration is not subtle. The presence of the grey box is a clear indicator of digital editing."
}
```
```json
{
  "verdict": "tampered",
  "confidence": "high",
  "reasoning": "A baseline analysis of the document shows that the majority of the text is black, uses a consistent sans-serif Thai font, and is set against a plain white background. However, a significant and obvious deviation exists in the date line. The year, '๒๕๖๘', is rendered in a different font style, is white instead of black, and is placed inside a solid purple rectangular box. This combination of inconsistent font, color, and background element is a clear and unambiguous indicator of digital modification or insertion after the original document was created.",
  "signals_detected": [
    {
      "signal_type": "color_contrast_discontinuity",
      "location": "The year '๒๕๖๘' in the date line, which is white text on a purple background, contrasting with the rest of the document's black text on a white background.",
      "severity": "high"
    },
    {
      "signal_type": "font_weight_inconsistency",
      "location": "The year '๒๕๖๘' in the date line appears to be a different font from the number '๙' on the same line and other numbers in the document.",
      "severity": "high"
    },
    {
      "signal_type": "shadow_edge_anomaly",
      "location": "The solid purple box behind the year '๒๕๖๘' has unnaturally sharp edges and is an isolated background element not found anywhere else in the document.",
      "severity": "high"
    }
  ],
  "notes": "The alteration is highly conspicuous and appears to be a deliberate insertion of a colored box with text, rather than a subtle attempt to change the date."
}
```
```json
{
  "verdict": "tampered",
  "confidence": "high",
  "reasoning": "The document exhibits two clear instances of digital alteration. The baseline typography is a consistent black font on a white background. However, two specific data points—the month and year in the date line, and the numerical loan amount in the main paragraph—are presented as white text within solid grey rectangular boxes. These boxes are visually jarring overlays that are inconsistent with the rest of the document's style. They have sharp digital edges and create a stark color and contrast discontinuity, indicating that the original text in these locations was obscured and replaced.",
  "signals_detected": [
    {
      "signal_type": "color_contrast_discontinuity",
      "location": "The date line, where the month and year ('พฤศจิกายน ๒๕๖๙') are displayed as white text inside a grey box.",
      "severity": "high"
    },
    {
      "signal_type": "color_contrast_discontinuity",
      "location": "The main paragraph, where the numerical loan amount ('๖๐๐,๐๐๐') is displayed as white text inside a grey box.",
      "severity": "high"
    }
  ],
  "notes": "The alterations appear to be redaction boxes placed over the original data. The textual amount '(ห้าแสนบาทถ้วน)' which translates to '(five hundred thousand baht exactly)' contradicts the altered numerical amount '๖๐๐,๐๐๐' (six hundred thousand), further suggesting manipulation, although this is a logical rather than purely visual signal."
}
```
```json
{
  "verdict": "tampered",
  "confidence": "high",
  "reasoning": "A baseline analysis of the document shows that the majority of the text is sharp, high-contrast, and typographically consistent. However, the numerical value '๕๐๐,๐๐๐' in the main body paragraph deviates significantly from this baseline. These numbers are visibly blurrier and have a lower resolution than the adjacent text 'จำนวนเงินกู้' and 'บาท'. Furthermore, the color of the numbers is a lighter, greyish-black compared to the deep black of the surrounding characters, and there is a subtle but distinct pixelated halo in the background around the digits. These combined signals strongly indicate that the original number was replaced with a digitally inserted image. Less severe, but still noticeable, resolution mismatches are also present in the numbers of the date ('๒๕๖๙') and the postal code ('๕๐๓๐๐'), suggesting a pattern of numerical alteration.",
  "signals_detected": [
    {
      "signal_type": "resolution_mismatch",
      "location": "The number '๕๐๐,๐๐๐' in the main body paragraph is significantly blurrier and more pixelated than the surrounding text.",
      "severity": "high"
    },
    {
      "signal_type": "color_contrast_discontinuity",
      "location": "The number '๕๐๐,๐๐๐' in the main body paragraph is a lighter shade of black/grey compared to the adjacent text.",
      "severity": "high"
    },
    {
      "signal_type": "shadow_edge_anomaly",
      "location": "A faint pixelated box or halo is visible in the white background immediately surrounding the digits '๕๐๐,๐๐๐'.",
      "severity": "medium"
    },
    {
      "signal_type": "resolution_mismatch",
      "location": "The numbers '๒๕๖๙' in the date line appear slightly less sharp than the surrounding text.",
      "severity": "low"
    }
  ],
  "notes": "The evidence for tampering is most conclusive around the loan amount. The other minor inconsistencies in numerical fields support the overall finding of digital modification."
}
```
```json
{
  "verdict": "tampered",
  "confidence": "high",
  "reasoning": "A baseline for the document's typography was established by examining the main body of text, which is consistent in font weight, sharpness, and resolution. Upon closer inspection of the date line, the numbers for the day ('๙') and the year ('๒๕๖๙') exhibit clear inconsistencies. These numbers are visibly bolder and have a different pixelation quality and edge sharpness compared to the surrounding text ('วันที่', 'พฤศจิกายน') and other numbers within the document (e.g., '๕๐๐,๐๐๐'). This localized difference strongly suggests that the original date numbers were digitally replaced.",
  "signals_detected": [
    {
      "signal_type": "font_weight_inconsistency",
      "location": "The numbers '๙' and '๒๕๖๙' in the date line.",
      "severity": "high"
    },
    {
      "signal_type": "resolution_mismatch",
      "location": "The numbers '๙' and '๒๕๖๙' in the date line, which have sharper, more pixelated edges than the surrounding text.",
      "severity": "high"
    }
  ],
  "notes": "The alteration appears to be confined to the numerical components of the date. The month text seems consistent with the rest of the document."
}
```
```json
{
  "verdict": "tampered",
  "confidence": "high",
  "reasoning": "1. The overall document uses a consistent serif Thai font (e.g., TH Sarabun style), establishing a clear typographic baseline.\n2. The numerical value '๖๐๐,๐๐๐' deviates significantly from this baseline. It is rendered in a sans-serif font, which is inconsistent with the serif font used for all surrounding Thai characters.\n3. The numerals also exhibit a lower resolution and different anti-aliasing (edge smoothing) compared to the crisp, sharp characters immediately adjacent to them, such as 'กู้' and 'บาท'.\n4. The combination of a font family mismatch and a resolution mismatch in the same location provides strong evidence that the number '๖๐๐,๐๐๐' was digitally inserted after the original document was created.",
  "signals_detected": [
    {
      "signal_type": "other",
      "location": "The numerals '๖๐๐,๐๐๐' are in a sans-serif font, while the rest of the document's text is in a serif font.",
      "severity": "high"
    },
    {
      "signal_type": "resolution_mismatch",
      "location": "The numerals '๖๐๐,๐๐๐' appear slightly blurrier and have different edge quality compared to the adjacent Thai characters.",
      "severity": "medium"
    }
  ],
  "notes": "The logical inconsistency between the numeral '๖๐๐,๐๐๐' (600,000) and the written-out amount '(ห้าแสนบาทถ้วน)' (five hundred thousand baht) further supports the conclusion of alteration, although the verdict is based solely on the visual signals."
}
```

## Review logged results

Load the full log (all batches) or just the current `BATCH_ID` to compare prompts/models without re-running anything.

In [26]:
df_all = load_results()
df_all[["timestamp", "batch_id", "image_path", "prompt_id", "model", "verdict", "confidence", "signal_types", "format", "latency_s"]]

,timestamp,batch_id,image_path,prompt_id,model,verdict,confidence,signal_types,format,latency_s
0,2026-06-11T02:20:36.332953+00:00,batch1,test_images/First_Tamper.png,V1,gemini-2.5-flash,authentic,high,[],True,9.42
1,2026-06-11T02:20:47.181659+00:00,batch1,test_images/first-tamper.png,V1,gemini-2.5-flash,tampered,medium,[resolution_mismatch],True,10.85
2,2026-06-11T02:20:53.951337+00:00,batch1,test_images/First_Tamper.png,V1_split,gemini-2.5-flash,authentic,high,[],True,6.76
3,2026-06-11T02:21:04.694144+00:00,batch1,test_images/first-tamper.png,V1_split,gemini-2.5-flash,authentic,high,[],True,10.74
4,2026-06-11T02:24:43.831825+00:00,batch1,test_images/First_Tamper.png,V1,gemini-2.5-flash,authentic,high,[],True,9.18
...,...,...,...,...,...,...,...,...,...,...
75,2026-06-11T07:51:36.241138+00:00,batch1,test_images/pink.png,V1_split,gemini-2.5-pro,tampered,high,"[color_contrast_discontinuity, font_weight_inc...",True,18.18
76,2026-06-11T07:51:57.597558+00:00,batch1,test_images/combined.png,V1_split,gemini-2.5-pro,tampered,high,"[color_contrast_discontinuity, color_contrast_...",True,21.35
77,2026-06-11T07:52:22.938434+00:00,batch1,test_images/neat.png,V1_split,gemini-2.5-pro,tampered,high,"[resolution_mismatch, color_contrast_discontin...",True,25.34
78,2026-06-11T07:52:46.607797+00:00,batch1,test_images/neatest.png,V1_split,gemini-2.5-pro,tampered,high,"[font_weight_inconsistency, resolution_mismatch]",True,23.67
79,2026-06-11T07:53:09.237077+00:00,batch1,test_images/cropped-obvious.png,V1_split,gemini-2.5-pro,tampered,high,"[other, resolution_mismatch]",True,22.63

In [27]:
df_all.columns

Index(['timestamp', 'batch_id', 'image_path', 'prompt_id', 'model',
       'temperature', 'latency_s', 'raw_response', 'parsed_response', 'notes',
       'label', 'label_signals', 'verdict', 'confidence', 'signal_types',
       'format'],
      dtype='object')

In [28]:
df_all[df_all['batch_id'] == 'batch1']

,timestamp,batch_id,image_path,prompt_id,model,temperature,latency_s,raw_response,parsed_response,notes,label,label_signals,verdict,confidence,signal_types,format
0,2026-06-11T02:20:36.332953+00:00,batch1,test_images/First_Tamper.png,V1,gemini-2.5-flash,0.10,9.42,"```json\n{\n ""verdict"": ""authentic"",\n ""conf...","{'verdict': 'authentic', 'confidence': 'high',...",,authentic,[],authentic,high,[],True
1,2026-06-11T02:20:47.181659+00:00,batch1,test_images/first-tamper.png,V1,gemini-2.5-flash,0.10,10.85,"```json\n{\n ""verdict"": ""tampered"",\n ""confi...","{'verdict': 'tampered', 'confidence': 'medium'...",,tampered,"[background_overlay, font_weight_inconsistency]",tampered,medium,[resolution_mismatch],True
2,2026-06-11T02:20:53.951337+00:00,batch1,test_images/First_Tamper.png,V1_split,gemini-2.5-flash,0.10,6.76,"```json\n{\n ""verdict"": ""authentic"",\n ""conf...","{'verdict': 'authentic', 'confidence': 'high',...",,authentic,[],authentic,high,[],True
3,2026-06-11T02:21:04.694144+00:00,batch1,test_images/first-tamper.png,V1_split,gemini-2.5-flash,0.10,10.74,"```json\n{\n ""verdict"": ""authentic"",\n ""conf...","{'verdict': 'authentic', 'confidence': 'high',...",,tampered,"[background_overlay, font_weight_inconsistency]",authentic,high,[],True
4,2026-06-11T02:24:43.831825+00:00,batch1,test_images/First_Tamper.png,V1,gemini-2.5-flash,0.05,9.18,"```json\n{\n ""verdict"": ""authentic"",\n ""conf...","{'verdict': 'authentic', 'confidence': 'high',...",,authentic,[],authentic,high,[],True
5,2026-06-11T02:24:51.311197+00:00,batch1,test_images/first-tamper.png,V1,gemini-2.5-flash,0.05,7.48,"```json\n{\n ""verdict"": ""authentic"",\n ""conf...","{'verdict': 'authentic', 'confidence': 'high',...",,tampered,"[background_overlay, font_weight_inconsistency]",authentic,high,[],True
6,2026-06-11T02:25:08.611948+00:00,batch1,test_images/combined.png,V1,gemini-2.5-flash,0.05,17.30,"```json\n{\n ""verdict"": ""tampered"",\n ""confi...","{'verdict': 'tampered', 'confidence': 'high', ...",,tampered,"[background_overlay, font_weight_inconsistency]",tampered,high,"[background_anomaly, background_anomaly]",False
7,2026-06-11T02:25:16.513412+00:00,batch1,test_images/neat.png,V1,gemini-2.5-flash,0.05,7.90,"```json\n{\n ""verdict"": ""authentic"",\n ""conf...","{'verdict': 'authentic', 'confidence': 'high',...",,tampered,"[font_weight_inconsistency, baseline_mismatch]",authentic,high,[],True
8,2026-06-11T02:25:28.105398+00:00,batch1,test_images/neatest.png,V1,gemini-2.5-flash,0.05,11.59,"```json\n{\n ""verdict"": ""tampered"",\n ""confi...","{'verdict': 'tampered', 'confidence': 'medium'...",,tampered,[font_weight_inconsistency],tampered,medium,[font_weight_inconsistency],True
9,2026-06-11T02:25:42.508209+00:00,batch1,test_images/cropped-obvious.png,V1,gemini-2.5-flash,0.05,14.40,"```json\n{\n ""verdict"": ""authentic"",\n ""conf...","{'verdict': 'authentic', 'confidence': 'high',...",,tampered,"[background_overlay, font_weight_inconsistency...",authentic,high,[],True
10,2026-06-11T02:25:57.621506+00:00,batch1,test_images/First_Tamper.png,V1_split,gemini-2.5-flash,0.10,15.10,"```json\n{\n ""verdict"": ""authentic"",\n ""conf...","{'verdict': 'authentic', 'confidence': 'high',...",,authentic,[],authentic,high,[],True
11,2026-06-11T02:26:14.541774+00:00,batch1,test_images/first-tamper.png,V1_split,gemini-2.5-flash,0.10,16.92,"```json\n{\n ""verdict"": ""tampered"",\n ""confi...","{'verdict': 'tampered', 'confidence': 'high', ...",,tampered,"[background_overlay, font_weight_inconsistency]",tampered,high,[color_contrast_discontinuity],True
12,2026-06-11T02:26:25.106080+00:00,batch1,test_images/combined.png,V1_split,gemini-2.5-flash,0.10,10.56,"```json\n{\n ""verdict"": ""tampered"",\n ""confi...","{'verdict': 'tampered', 'confidence': 'high', ...",,tampered,"[background_overlay, font_weight_inconsistency]",tampered,high,[shadow_edge_anomaly],True
13,2026-06-11T02:26:36.165434+00:00,batch1,test_images/neat.png,V1_split,gemini-2.5-flash,0.10,11.06,"```json\n{\n ""verdict"": ""authentic"",\n ""conf...","{'verdict': 'authentic', 'confidence': 'high',...",,tampered,"[font_weight_inconsistency, baseline_mismatch]",authentic,high,[],True
14,2026-06-11T02:26:45.586293+00:00,batch1,test_images/neatest.png,V1_split,gemini-2.5-flash,0.10,9.42,"```json\n{\n ""verdict"": ""authentic"",\n ""conf...","{'verdict': 'authentic', 'confidence': 'high',...",,tampered,[font_weight_inconsistency],authentic,high,[],True
15,2026-06-11T02:27:10.118903+00:00,batch1,test_images/cropped-obvious.png,V1_split,gemini-2.5-flash,0.10,24.53,"```json\n{\n ""verdict"": ""tampered"",\n ""confi...","{'verdict': 'tampered', 'confidence': 'high', ...",,tampered,"[background_overlay, font_weight_inconsistency...",tampered,high,"[color_contrast_discontinuity, shadow_edge_ano...",True
16,2026-06-11T02:29:12.862211+00:00,batch1,test_images/First_Tamper.png,V1,gemini-2.5-flash,0.05,10.80,"```json\n{\n ""verdict"": ""authentic"",\n ""conf...","{'verdict': 'authentic', 'confidence': 'high',...",,authentic,[],authentic,high,[],True
17,2026-06-11T02:29:22.259282+00:00,batch1,test_images/first-tamper.png,V1,gemini-2.5-flash,0.05,9.39,"```json\n{\n ""verdict"": ""authentic"",\n ""conf...","{'verdict': 'authentic', 'confidence': 'high',...",,tampered,"[background_overlay, font_weight_inconsistency]",authentic,high,[],True
18,2026-06-11T02:29:33.560048+00:00,batch1,test_images/pink.png,V1,gemini-2.5-flash,0.05,11.30,"```json\n{\n ""verdict"": ""tampered"",\n ""confi...","{'verdict': 'tampered', 'confidence': 'high', ...",,tampered,"[background_overlay, font_weight_inconsistency]",tampered,high,[color_contrast_discontinuity],True
19,2026-06-11T02:29:47.538975+00:00,batch1,test_images/combined.png,V1,gemini-2.5-flash,0.05,13.98,"```json\n{\n ""verdict"": ""tampered"",\n ""confi...","{'verdict': 'tampered', 'confidence': 'high', ...",,tampered,"[background_overlay, font_weight_inconsistency]",tampered,high,"[color_contrast_discontinuity, color_contrast_...",True
20,2026-06-11T02:30:00.319111+00:00,batch1,test_images/neat.png,V1,gemini-2.5-flash,0.05,12.78,"```json\n{\n ""verdict"": ""authentic"",\n ""conf...","{'verdict': 'authentic', 'confidence': 'high',...",,tampered,"[font_weight_inconsistency, baseline_mismatch]",authentic,high,[],True
21,2026-06-11T02:30:10.152412+00:00,batch1,test_images/neatest.png,V1,gemini-2.5-flash,0.05,9.83,"```json\n{\n ""verdict"": ""authentic"",\n ""conf...","{'verdict': 'authentic', 'confidence': 'high',...",,tampered,[font_weight_inconsistency],authentic,high,[],True
22,2026-06-11T02:30:24.219643+00:00,batch1,test_images/cropped-obvious.png,V1,gemini-2.5-flash,0.05,14.07,"```json\n{\n ""verdict"": ""tampered"",\n ""confi...","{'verdict': 'tampered', 'confidence': 'high', ...",,tampered,"[background_overlay, font_weight_inconsistency...",tampered,high,"[shadow_edge_anomaly, resolution_mismatch]",True
23,2026-06-11T02:30:30.932690+00:00,batch1,test_images/First_Tamper.png,V1_split,gemini-2.5-flash,0.10,6.70,"```json\n{\n ""verdict"": ""authentic"",\n ""conf...","{'verdict': 'authentic', 'confidence': 'high',...",,authentic,[],authentic,high,[],True
24,2026-06-11T02:30:37.581547+00:00,batch1,test_images/first-tamper.png,V1_split,gemini-2.5-flash,0.10,6.65,"```json\n{\n ""verdict"": ""authentic"",\n ""conf...","{'verdict': 'authentic', 'confidence': 'high',...",,tampered,"[background_overlay, font_weight_inconsistency]",authentic,high,[],True
25,2026-06-11T02:30:45.917864+00:00,batch1,test_images/pink.png,V1_split,gemini-2.5-flash,0.10,8.33,"```json\n{\n ""verdict"": ""tampered"",\n ""confi...","{'verdict': 'tampered', 'confidence': 'high', ...",,tampered,"[background_overlay, font_weight_inconsistency]",tampered,high,"[color_contrast_discontinuity, shadow_edge_ano...",True
26,2026-06-11T02:30:56.508653+00:00,batch1,test_images/combined.png,V1_split,gemini-2.5-flash,0.10,10.59,"```json\n{\n ""verdict"": ""tampered"",\n ""confi...","{'verdict': 'tampered', 'confidence': 'high', ...",,tampered,"[background_overlay, font_weight_inconsistency]",tampered,high,"[color_contrast_discontinuity, font_weight_inc...",True
27,2026-06-11T02:31:11.593313+00:00,batch1,test_images/neat.png,V1_split,gemini-2.5-flash,0.10,15.08,"```json\n{\n ""verdict"": ""authentic"",\n ""conf...","{'verdict': 'authentic', 'confidence': 'high',...",,tampered,"[font_weight_inconsistency, baseline_mismatch]",authentic,high,[],True
28,2026-06-11T02:31:20.461188+00:00,batch1,test_images/neatest.png,V1_split,gemini-2.5-flash,0.10,8.87,"```json\n{\n ""verdict"": ""authentic"",\n ""conf...","{'verdict': 'authentic', 'confidence': 'high',...",,tampered,[font_weight_inconsistency],authentic,high,[],True
29,2026-06-11T02:31:32.640757+00:00,batch1,test_images/cropped-obvious.png,V1_split,gemini-2.5-flash,0.10,12.18,"```json\n{\n ""verdict"": ""authentic"",\n ""conf...","{'verdict': 'authentic', 'confidence': 'high',...",,tampered,"[background_overlay, font_weight_inconsistency...",authentic,high,[],True
66,2026-06-11T07:48:02.637209+00:00,batch1,test_images/First_Tamper.png,V1,gemini-2.5-pro,0.10,16.53,"```json\n{\n ""verdict"": ""authentic"",\n ""conf...","{'verdict': 'authentic', 'confidence': 'high',...",,authentic,[],authentic,high,[],True
67,2026-06-11T07:48:21.578331+00:00,batch1,test_images/first-tamper.png,V1,gemini-2.5-pro,0.10,18.94,"```json\n{\n ""verdict"": ""tampered"",\n ""confi...","{'verdict': 'tampered', 'confidence': 'high', ...",,tampered,"[background_overlay, font_weight_inconsistency]",tampered,high,[color_contrast_discontinuity],True
68,2026-06-11T07:48:48.921455+00:00,batch1,test_images/pink.png,V1,gemini-2.5-pro,0.10,27.34,"```json\n{\n ""verdict"": ""tampered"",\n ""confi...","{'verdict': 'tampered', 'confidence': 'high', ...",,tampered,"[background_overlay, font_weight_inconsistency]",tampered,high,"[color_contrast_discontinuity, resolution_mism...",True
69,2026-06-11T07:49:19.329964+00:00,batch1,test_images/combined.png,V1,gemini-2.5-pro,0.10,30.41,"```json\n{\n ""verdict"": ""tampered"",\n ""confi...","{'verdict': 'tampered', 'confidence': 'high', ...",,tampered,"[background_overlay, font_weight_inconsistency]",tampered,high,"[color_contrast_discontinuity, color_contrast_...",True
70,2026-06-11T07:49:42.499963+00:00,batch1,test_images/neat.png,V1,gemini-2.5-pro,0.10,23.17,"```json\n{\n ""verdict"": ""tampered"",\n ""confi...","{'verdict': 'tampered', 'confidence': 'high', ...",,tampered,"[font_weight_inconsistency, baseline_mismatch]",tampered,high,[font_weight_inconsistency],True
71,2026-06-11T07:50:07.156479+00:00,batch1,test_images/neatest.png,V1,gemini-2.5-pro,0.10,24.65,"```json\n{\n ""verdict"": ""tampered"",\n ""confi...","{'verdict': 'tampered', 'confidence': 'high', ...",,tampered,[font_weight_inconsistency],tampered,high,"[resolution_mismatch, resolution_mismatch]",True
72,2026-06-11T07:50:42.498499+00:00,batch1,test_images/cropped-obvious.png,V1,gemini-2.5-pro,0.10,35.34,"```json\n{\n ""verdict"": ""tampered"",\n ""confi...","{'verdict': 'tampered', 'confidence': 'high', ...",,tampered,"[background_overlay, font_weight_inconsistency...",tampered,high,"[other, resolution_mismatch]",True
73,2026-06-11T07:51:00.810120+00:00,batch1,test_images/First_Tamper.png,V1_split,gemini-2.5-pro,0.10,18.28,"```json\n{\n ""verdict"": ""authentic"",\n ""conf...","{'verdict': 'authentic', 'confidence': 'high',...",,authentic,[],authentic,high,[],True
74,2026-06-11T07:51:18.060422+00:00,batch1,test_images/first-tamper.png,V1_split,gemini-2.5-pro,0.10,17.25,"```json\n{\n ""verdict"": ""tampered"",\n ""confi...","{'verdict': 'tampered', 'confidence': 'high', ...",,tampered,"[background_overlay, font_weight_inconsistency]",tampered,high,[color_contrast_discontinuity],True
75,2026-06-11T07:51:36.241138+00:00,batch1,test_images/pink.png,V1_split,gemini-2.5-pro,0.10,18.18,"```json\n{\n ""verdict"": ""tampered"",\n ""confi...","{'verdict': 'tampered', 'confidence': 'high', ...",,tampered,"[background_overlay, font_weight_inconsistency]",tampered,high,"[color_contrast_discontinuity, font_weight_inc...",True
76,2026-06-11T07:51:57.597558+00:00,batch1,test_images/combined.png,V1_split,gemini-2.5-pro,0.10,21.35,"```json\n{\n ""verdict"": ""tampered"",\n ""confi...","{'verdict': 'tampered', 'confidence': 'high', ...",,tampered,"[background_overlay, font_weight_inconsistency]",tampered,high,"[color_contrast_discontinuity, color_contrast_...",True
77,2026-06-11T07:52:22.938434+00:00,batch1,test_images/neat.png,V1_split,gemini-2.5-pro,0.10,25.34,"```json\n{\n ""verdict"": ""tampered"",\n ""confi...","{'verdict': 'tampered', 'confidence': 'high', ...",,tampered,"[font_weight_inconsistency, baseline_mismatch]",tampered,high,"[resolution_mismatch, color_contrast_discontin...",True
78,2026-06-11T07:52:46.607797+00:00,batch1,test_images/neatest.png,V1_split,gemini-2.5-pro,0.10,23.67,"```json\n{\n ""verdict"": ""tampered"",\n ""confi...","{'verdict': 'tampered', 'confidence': 'high', ...",,tampered,[font_weight_inconsistency],tampered,high,"[font_weight_inconsistency, resolution_mismatch]",True
79,2026-06-11T07:53:09.237077+00:00,batch1,test_images/cropped-obvious.png,V1_split,gemini-2.5-pro,0.10,22.63,"```json\n{\n ""verdict"": ""tampered"",\n ""confi...","{'verdict': 'tampered', 'confidence': 'high', ...",,tampered,"[background_overlay, font_weight_inconsistency...",tampered,high,"[other, resolution_mismatch]",True

In [35]:
# Calculate some accuracy, recall, F1 metrics
total_tests = len(df_all)
total_wrong_verdict = len(df_all[df_all['label'] != df_all['verdict']])

print("Wrong_verdict_percent", total_wrong_verdict/total_tests*100)

Wrong_verdict_percent 35.0

### Different batches will be different I am sure

In [41]:
df_all['verdict'].value_counts()

verdict
tampered        40
authentic       39
inconclusive     1
Name: count, dtype: int64

In [39]:
df_all[(df_all['verdict'] == 'inconclusive')]

,timestamp,batch_id,image_path,prompt_id,model,temperature,latency_s,raw_response,parsed_response,notes,label,label_signals,verdict,confidence,signal_types,format
42,2026-06-11T06:06:48.188613+00:00,batch2,test_images/payslip1.jpeg,V1,gemini-2.5-flash,0.05,31.21,"```json\n{\n ""verdict"": ""inconclusive"",\n ""c...","{'verdict': 'inconclusive', 'confidence': 'hig...",,tampered,"[font_weight_inconsistency, font_size_mismatch...",inconclusive,high,[font_weight_inconsistency],True

In [43]:
from analysis_util import compute_binary_metrics
total_matrics = compute_binary_metrics(df_all)
print(total_matrics)

precision          0.825000
recall             0.622642
specificity        0.730769
f1                 0.709677
accuracy           0.658228
true_positive     33.000000
false_positive     7.000000
false_negative    20.000000
true_negative     19.000000
excluded_count     1.000000
dtype: float64

#### Batch 1

In [46]:
batch1 = df_all[df_all['batch_id'] =='batch1']
print(compute_binary_metrics(batch1))

precision          1.000000
recall             0.638889
specificity        1.000000
f1                 0.779661
accuracy           0.704545
true_positive     23.000000
false_positive     0.000000
false_negative    13.000000
true_negative      8.000000
excluded_count     0.000000
dtype: float64

#### Batch 2

In [48]:
batch2 = df_all[df_all['batch_id'] =='batch2']
print(compute_binary_metrics(batch2))

precision          0.588235
recall             0.588235
specificity        0.611111
f1                 0.588235
accuracy           0.600000
true_positive     10.000000
false_positive     7.000000
false_negative     7.000000
true_negative     11.000000
excluded_count     1.000000
dtype: float64

In [49]:
batch2

,timestamp,batch_id,image_path,prompt_id,model,temperature,latency_s,raw_response,parsed_response,notes,label,label_signals,verdict,confidence,signal_types,format
30,2026-06-11T05:19:42.981923+00:00,batch2,test_images/payslip1.jpeg,V1,gemini-2.5-flash,0.05,14.50,"```json\n{\n ""verdict"": ""authentic"",\n ""conf...","{'verdict': 'authentic', 'confidence': 'high',...",,tampered,"[font_weight_inconsistency, font_size_mismatch...",authentic,high,[],True
31,2026-06-11T05:19:57.928182+00:00,batch2,test_images/payslip10.jpeg,V1,gemini-2.5-flash,0.05,14.94,"```json\n{\n ""verdict"": ""authentic"",\n ""conf...","{'verdict': 'authentic', 'confidence': 'high',...",,authentic,[],authentic,high,[],True
32,2026-06-11T05:20:29.880469+00:00,batch2,test_images/payslip2.png,V1,gemini-2.5-flash,0.05,31.95,"```json\n{\n ""verdict"": ""tampered"",\n ""confi...","{'verdict': 'tampered', 'confidence': 'medium'...",,tampered,"[font_weight_inconsistency, font_size_mismatch...",tampered,medium,"[font_weight_inconsistency, sharpness_inconsis...",False
33,2026-06-11T05:20:41.214401+00:00,batch2,test_images/payslip20.png,V1,gemini-2.5-flash,0.05,11.33,"```json\n{\n ""verdict"": ""tampered"",\n ""confi...","{'verdict': 'tampered', 'confidence': 'high', ...",,authentic,[],tampered,high,[font_weight_inconsistency],True
34,2026-06-11T05:21:01.187514+00:00,batch2,test_images/payslip3.png,V1,gemini-2.5-flash,0.05,19.97,"```json\n{\n ""verdict"": ""tampered"",\n ""confi...","{'verdict': 'tampered', 'confidence': 'high', ...",,tampered,"[font_weight_inconsistency, font_size_mismatch...",tampered,high,"[font_weight_inconsistency, font_mismatch]",False
35,2026-06-11T05:21:12.680004+00:00,batch2,test_images/payslip30.png,V1,gemini-2.5-flash,0.05,11.49,"```json\n{\n ""verdict"": ""authentic"",\n ""conf...","{'verdict': 'authentic', 'confidence': 'high',...",,authentic,[],authentic,high,[],True
36,2026-06-11T05:21:27.553605+00:00,batch2,test_images/payslip1.jpeg,V1_split,gemini-2.5-flash,0.10,14.81,"```json\n{\n ""verdict"": ""tampered"",\n ""confi...","{'verdict': 'tampered', 'confidence': 'medium'...",,tampered,"[font_weight_inconsistency, font_size_mismatch...",tampered,medium,[font_weight_inconsistency],True
37,2026-06-11T05:21:38.359619+00:00,batch2,test_images/payslip10.jpeg,V1_split,gemini-2.5-flash,0.10,10.80,"```json\n{\n ""verdict"": ""authentic"",\n ""conf...","{'verdict': 'authentic', 'confidence': 'high',...",,authentic,[],authentic,high,[],True
38,2026-06-11T05:21:51.724211+00:00,batch2,test_images/payslip2.png,V1_split,gemini-2.5-flash,0.10,13.36,"```json\n{\n ""verdict"": ""tampered"",\n ""confi...","{'verdict': 'tampered', 'confidence': 'high', ...",,tampered,"[font_weight_inconsistency, font_size_mismatch...",tampered,high,"[font_weight_inconsistency, resolution_mismatc...",True
39,2026-06-11T05:22:03.067231+00:00,batch2,test_images/payslip20.png,V1_split,gemini-2.5-flash,0.10,11.34,"```json\n{\n ""verdict"": ""tampered"",\n ""confi...","{'verdict': 'tampered', 'confidence': 'high', ...",,authentic,[],tampered,high,"[font_weight_inconsistency, resolution_mismatc...",True
40,2026-06-11T05:22:20.543250+00:00,batch2,test_images/payslip3.png,V1_split,gemini-2.5-flash,0.10,17.47,"```json\n{\n ""verdict"": ""tampered"",\n ""confi...","{'verdict': 'tampered', 'confidence': 'high', ...",,tampered,"[font_weight_inconsistency, font_size_mismatch...",tampered,high,"[font_weight_inconsistency, resolution_mismatc...",True
41,2026-06-11T05:22:32.554770+00:00,batch2,test_images/payslip30.png,V1_split,gemini-2.5-flash,0.10,12.01,"```json\n{\n ""verdict"": ""authentic"",\n ""conf...","{'verdict': 'authentic', 'confidence': 'high',...",,authentic,[],authentic,high,[],True
42,2026-06-11T06:06:48.188613+00:00,batch2,test_images/payslip1.jpeg,V1,gemini-2.5-flash,0.05,31.21,"```json\n{\n ""verdict"": ""inconclusive"",\n ""c...","{'verdict': 'inconclusive', 'confidence': 'hig...",,tampered,"[font_weight_inconsistency, font_size_mismatch...",inconclusive,high,[font_weight_inconsistency],True
43,2026-06-11T06:07:02.617062+00:00,batch2,test_images/payslip10.jpeg,V1,gemini-2.5-flash,0.05,14.43,"```json\n{\n ""verdict"": ""authentic"",\n ""conf...","{'verdict': 'authentic', 'confidence': 'high',...",,authentic,[],authentic,high,[],True
44,2026-06-11T06:07:17.293611+00:00,batch2,test_images/payslip2.png,V1,gemini-2.5-flash,0.05,14.67,"```json\n{\n ""verdict"": ""tampered"",\n ""confi...","{'verdict': 'tampered', 'confidence': 'high', ...",,tampered,"[font_weight_inconsistency, font_size_mismatch...",tampered,high,[font_weight_inconsistency],True
45,2026-06-11T06:07:30.973995+00:00,batch2,test_images/payslip20.png,V1,gemini-2.5-flash,0.05,13.68,"```json\n{\n ""verdict"": ""tampered"",\n ""confi...","{'verdict': 'tampered', 'confidence': 'high', ...",,authentic,[],tampered,high,"[font_weight_inconsistency, resolution_mismatch]",True
46,2026-06-11T06:08:26.503508+00:00,batch2,test_images/payslip3.png,V1,gemini-2.5-flash,0.05,55.53,"```json\n{\n ""verdict"": ""authentic"",\n ""conf...","{'verdict': 'authentic', 'confidence': 'high',...",,tampered,"[font_weight_inconsistency, font_size_mismatch...",authentic,high,[],True
47,2026-06-11T06:08:40.086208+00:00,batch2,test_images/payslip30.png,V1,gemini-2.5-flash,0.05,13.58,"```json\n{\n ""verdict"": ""authentic"",\n ""conf...","{'verdict': 'authentic', 'confidence': 'high',...",,authentic,[],authentic,high,[],True
48,2026-06-11T06:08:53.530226+00:00,batch2,test_images/payslip1.jpeg,V1,gemini-2.5-flash,0.05,13.43,"```json\n{\n ""verdict"": ""authentic"",\n ""conf...","{'verdict': 'authentic', 'confidence': 'high',...",,tampered,"[font_weight_inconsistency, font_size_mismatch...",authentic,high,[],True
49,2026-06-11T06:09:03.309490+00:00,batch2,test_images/payslip10.jpeg,V1,gemini-2.5-flash,0.05,9.78,"```json\n{\n ""verdict"": ""authentic"",\n ""conf...","{'verdict': 'authentic', 'confidence': 'high',...",,authentic,[],authentic,high,[],True
50,2026-06-11T06:09:22.598597+00:00,batch2,test_images/payslip2.png,V1,gemini-2.5-flash,0.05,19.29,"```json\n{\n ""verdict"": ""tampered"",\n ""confi...","{'verdict': 'tampered', 'confidence': 'high', ...",,tampered,"[font_weight_inconsistency, font_size_mismatch...",tampered,high,"[font_mismatch, font_weight_inconsistency, res...",False
51,2026-06-11T06:09:36.945015+00:00,batch2,test_images/payslip20.png,V1,gemini-2.5-flash,0.05,14.34,"```json\n{\n ""verdict"": ""tampered"",\n ""confi...","{'verdict': 'tampered', 'confidence': 'medium'...",,authentic,[],tampered,medium,"[font_weight_inconsistency, resolution_mismatch]",True
52,2026-06-11T06:09:55.274268+00:00,batch2,test_images/payslip3.png,V1,gemini-2.5-flash,0.05,18.33,"```json\n{\n ""verdict"": ""tampered"",\n ""confi...","{'verdict': 'tampered', 'confidence': 'high', ...",,tampered,"[font_weight_inconsistency, font_size_mismatch...",tampered,high,"[font_size_mismatch, font_weight_inconsistency...",True
53,2026-06-11T06:10:09.201988+00:00,batch2,test_images/payslip30.png,V1,gemini-2.5-flash,0.05,13.93,"```json\n{\n ""verdict"": ""authentic"",\n ""conf...","{'verdict': 'authentic', 'confidence': 'high',...",,authentic,[],authentic,high,[],True
54,2026-06-11T06:28:15.209886+00:00,batch2,test_images/payslip1.jpeg,V1,gemini-2.5-flash,0.05,13.68,"```json\n{\n ""verdict"": ""authentic"",\n ""conf...","{'verdict': 'authentic', 'confidence': 'high',...",,tampered,"[font_weight_inconsistency, font_size_mismatch...",authentic,high,[],True
55,2026-06-11T06:28:25.712467+00:00,batch2,test_images/payslip10.jpeg,V1,gemini-2.5-flash,0.05,10.50,"```json\n{\n ""verdict"": ""authentic"",\n ""conf...","{'verdict': 'authentic', 'confidence': 'high',...",,authentic,[],authentic,high,[],True
56,2026-06-11T06:28:40.049280+00:00,batch2,test_images/payslip2.png,V1,gemini-2.5-flash,0.05,14.33,"```json\n{\n ""verdict"": ""tampered"",\n ""confi...","{'verdict': 'tampered', 'confidence': 'high', ...",,tampered,"[font_weight_inconsistency, font_size_mismatch...",tampered,high,"[font_size_mismatch, font_weight_inconsistency...",True
57,2026-06-11T06:28:52.131246+00:00,batch2,test_images/payslip20.png,V1,gemini-2.5-flash,0.05,12.08,"```json\n{\n ""verdict"": ""tampered"",\n ""confi...","{'verdict': 'tampered', 'confidence': 'medium'...",,authentic,[],tampered,medium,"[font_weight_inconsistency, resolution_mismatch]",True
58,2026-06-11T06:29:08.925317+00:00,batch2,test_images/payslip3.png,V1,gemini-2.5-flash,0.05,16.79,"```json\n{\n ""verdict"": ""tampered"",\n ""confi...","{'verdict': 'tampered', 'confidence': 'high', ...",,tampered,"[font_weight_inconsistency, font_size_mismatch...",tampered,high,"[font_weight_inconsistency, resolution_mismatc...",True
59,2026-06-11T06:29:24.490070+00:00,batch2,test_images/payslip30.png,V1,gemini-2.5-flash,0.05,15.56,"```json\n{\n ""verdict"": ""authentic"",\n ""conf...","{'verdict': 'authentic', 'confidence': 'high',...",,authentic,[],authentic,high,[],True
60,2026-06-11T06:29:35.551508+00:00,batch2,test_images/payslip1.jpeg,V1_split,gemini-2.5-flash,0.10,11.05,"```json\n{\n ""verdict"": ""authentic"",\n ""conf...","{'verdict': 'authentic', 'confidence': 'high',...",,tampered,"[font_weight_inconsistency, font_size_mismatch...",authentic,high,[],True
61,2026-06-11T06:29:43.637821+00:00,batch2,test_images/payslip10.jpeg,V1_split,gemini-2.5-flash,0.10,8.08,"```json\n{\n ""verdict"": ""authentic"",\n ""conf...","{'verdict': 'authentic', 'confidence': 'high',...",,authentic,[],authentic,high,[],True
62,2026-06-11T06:29:51.011143+00:00,batch2,test_images/payslip2.png,V1_split,gemini-2.5-flash,0.10,7.37,"```json\n{\n ""verdict"": ""authentic"",\n ""conf...","{'verdict': 'authentic', 'confidence': 'high',...",,tampered,"[font_weight_inconsistency, font_size_mismatch...",authentic,high,[],True
63,2026-06-11T06:30:08.111892+00:00,batch2,test_images/payslip20.png,V1_split,gemini-2.5-flash,0.10,17.10,"```json\n{\n ""verdict"": ""tampered"",\n ""confi...","{'verdict': 'tampered', 'confidence': 'high', ...",,authentic,[],tampered,high,"[font_weight_inconsistency, resolution_mismatc...",True
64,2026-06-11T06:30:20.810830+00:00,batch2,test_images/payslip3.png,V1_split,gemini-2.5-flash,0.10,12.70,"```json\n{\n ""verdict"": ""authentic"",\n ""conf...","{'verdict': 'authentic', 'confidence': 'high',...",,tampered,"[font_weight_inconsistency, font_size_mismatch...",authentic,high,[],True
65,2026-06-11T06:30:39.347482+00:00,batch2,test_images/payslip30.png,V1_split,gemini-2.5-flash,0.10,18.53,"```json\n{\n ""verdict"": ""tampered"",\n ""confi...","{'verdict': 'tampered', 'confidence': 'medium'...",,authentic,[],tampered,medium,"[font_weight_inconsistency, font_weight_incons...",True

#### If wanted to load only one batch for analysis

In [29]:
# current_batch = load_results(batch_id=BATCH_ID)
# current_batch[["image_path", "prompt_id", "verdict", "confidence", "signal_types", "format", "latency_s"]]